name: Publish NuGet

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history for tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Extract version from tag
        id: meta
        shell: bash
        run: |
          RAW="${GITHUB_REF_NAME}"
          VERSION="${RAW#v}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Restore
        run: dotnet restore ./TravelDocFaker/TravelDocFaker.csproj

      - name: Build (Release)
        run: dotnet build ./TravelDocFaker/TravelDocFaker.csproj -c Release --no-restore

      - name: Pack (force tag version)
        run: dotnet pack ./TravelDocFaker/TravelDocFaker.csproj -c Release --no-build -o ./artifacts /p:PackageVersion=${{ steps.meta.outputs.version }}

      - name: Publish to NuGet
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
